splash = false

wallpaper {
  monitor = DP-1
  path = $HOME/Pictures/Wallpapers/nightcore.jpg
  fit_mode = cover
}

wallpaper {
  monitor = DP-2
  path = $HOME/Pictures/Wallpapers/nightcore2.jpg
  fit_mode = cover
}
